services:

  db:
    image: postgres:15
    container_name: spacenet-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${BIND_HOST:-127.0.0.1}:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: spacenet-redis
    ports:
      - "${BIND_HOST:-127.0.0.1}:6379:6379"
    restart: unless-stopped

  backend:
    build: ./spacenet-backend
    container_name: spacenet-backend
    depends_on:
      - db
      - redis
    ports:
      - "${BIND_HOST:-127.0.0.1}:5000:5000"
    volumes:
      - ./spacenet-backend:/app
    env_file:
      - .env
    environment:
      - WATCHDOG_USE_POLLING=true
    restart: unless-stopped
    command: >
      bash -c "
      flask db upgrade &&
      flask run --host=0.0.0.0 --reload
      "

  worker:
    build: ./spacenet-backend
    container_name: spacenet-worker
    privileged: true
    depends_on:
      - redis
      - db
    volumes:
      - ./spacenet-backend:/app
    env_file:
      - .env
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - SHELL=/bin/bash
      - PYTHONPATH=/app/dynamic-topology-generator:/app
    command: rq worker default
    restart: unless-stopped

  worker_plot:
    build: ./spacenet-backend
    container_name: spacenet-worker-plot
    privileged: true
    depends_on:
      - redis
      - db
    volumes:
      - ./spacenet-backend:/app
    env_file:
      - .env
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - SHELL=/bin/bash
      - PYTHONPATH=/app/dynamic-topology-generator:/app
    command: rq worker plot
    restart: unless-stopped

  frontend:
    build: ./spacenet-gui
    container_name: spacenet-gui
    ports:
      - "${BIND_HOST:-127.0.0.1}:3000:3000"
    volumes:
      - ./spacenet-gui:/app
      - /app/node_modules
    command: npm run dev
    environment:
    - CHOKIDAR_USEPOLLING=true
    - WATCHPACK_POLLING=true
    restart: unless-stopped

volumes:
  postgres_data: