"""add custom config

Revision ID: c82eed34d17d
Revises: 26e8107f6cbf
Create Date: 2026-04-28 01:26:13.200681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82eed34d17d'
down_revision = '26e8107f6cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_custom', sa.Boolean(), nullable=False, server_default="FALSE"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_column('is_custom')

    # ### end Alembic commands ###
